//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADMIN
{
    using System;
    using System.Collections.Generic;
    
    public partial class History_tickets
    {
        public int ID_HT { get; set; }
        public string Login { get; set; }
        public int Flight_ID_HT { get; set; }
        public int Tickets_ID_HT { get; set; }
        public decimal Total_cost { get; set; }
        public string Status { get; set; }
    }
}
