//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADMIN
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int ID_Tickets { get; set; }
        public decimal Total_cost { get; set; }
        public int Passenger_ID { get; set; }
        public int Flight_ID { get; set; }
        public int Class_ID { get; set; }
        public int Age_ID { get; set; }
    
        public virtual Age Age { get; set; }
        public virtual Class_ticket Class_ticket { get; set; }
        public virtual Flight Flight { get; set; }
        public virtual Passenger Passenger { get; set; }
    }
}
